// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cri_msgs.proto
// Protobuf C++ Version: 6.31.1

#ifndef cri_5fmsgs_2eproto_2epb_2eh
#define cri_5fmsgs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cri_5fmsgs_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cri_5fmsgs_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cri_5fmsgs_2eproto;
}  // extern "C"
namespace Nrmk {
namespace IndyFramework {
class CriData;
struct CriDataDefaultTypeInternal;
extern CriDataDefaultTypeInternal _CriData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CriData_class_data_;
class SFDAccount;
struct SFDAccountDefaultTypeInternal;
extern SFDAccountDefaultTypeInternal _SFDAccount_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SFDAccount_class_data_;
class SFDAutoSet;
struct SFDAutoSetDefaultTypeInternal;
extern SFDAutoSetDefaultTypeInternal _SFDAutoSet_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SFDAutoSet_class_data_;
class SFDProjectList;
struct SFDProjectListDefaultTypeInternal;
extern SFDProjectListDefaultTypeInternal _SFDProjectList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SFDProjectList_class_data_;
class SFDTarget;
struct SFDTargetDefaultTypeInternal;
extern SFDTargetDefaultTypeInternal _SFDTarget_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SFDTarget_class_data_;
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Nrmk {
namespace IndyFramework {

// ===================================================================


// -------------------------------------------------------------------

class SFDTarget final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDTarget) */ {
 public:
  inline SFDTarget() : SFDTarget(nullptr) {}
  ~SFDTarget() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SFDTarget* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SFDTarget));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SFDTarget(::google::protobuf::internal::ConstantInitialized);

  inline SFDTarget(const SFDTarget& from) : SFDTarget(nullptr, from) {}
  inline SFDTarget(SFDTarget&& from) noexcept
      : SFDTarget(nullptr, ::std::move(from)) {}
  inline SFDTarget& operator=(const SFDTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDTarget& operator=(SFDTarget&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDTarget& default_instance() {
    return *reinterpret_cast<const SFDTarget*>(
        &_SFDTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SFDTarget& a, SFDTarget& b) { a.Swap(&b); }
  inline void Swap(SFDTarget* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDTarget* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDTarget* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SFDTarget>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDTarget& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SFDTarget& from) { SFDTarget::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SFDTarget* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Nrmk.IndyFramework.SFDTarget"; }

 protected:
  explicit SFDTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SFDTarget(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SFDTarget& from);
  SFDTarget(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SFDTarget&& from) noexcept
      : SFDTarget(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPnFieldNumber = 1,
    kFnFieldNumber = 2,
    kRnFieldNumber = 3,
    kIsoFieldNumber = 4,
  };
  // string pn = 1;
  void clear_pn() ;
  const ::std::string& pn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pn();
  void set_allocated_pn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pn();

  public:
  // string fn = 2;
  void clear_fn() ;
  const ::std::string& fn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fn();
  void set_allocated_fn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fn();

  public:
  // string rn = 3;
  void clear_rn() ;
  const ::std::string& rn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rn();
  void set_allocated_rn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rn();

  public:
  // bool iso = 4;
  void clear_iso() ;
  bool iso() const;
  void set_iso(bool value);

  private:
  bool _internal_iso() const;
  void _internal_set_iso(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDTarget)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SFDTarget& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pn_;
    ::google::protobuf::internal::ArenaStringPtr fn_;
    ::google::protobuf::internal::ArenaStringPtr rn_;
    bool iso_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SFDTarget_class_data_;
// -------------------------------------------------------------------

class SFDProjectList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDProjectList) */ {
 public:
  inline SFDProjectList() : SFDProjectList(nullptr) {}
  ~SFDProjectList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SFDProjectList* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SFDProjectList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SFDProjectList(::google::protobuf::internal::ConstantInitialized);

  inline SFDProjectList(const SFDProjectList& from) : SFDProjectList(nullptr, from) {}
  inline SFDProjectList(SFDProjectList&& from) noexcept
      : SFDProjectList(nullptr, ::std::move(from)) {}
  inline SFDProjectList& operator=(const SFDProjectList& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDProjectList& operator=(SFDProjectList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDProjectList& default_instance() {
    return *reinterpret_cast<const SFDProjectList*>(
        &_SFDProjectList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SFDProjectList& a, SFDProjectList& b) { a.Swap(&b); }
  inline void Swap(SFDProjectList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDProjectList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDProjectList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SFDProjectList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDProjectList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SFDProjectList& from) { SFDProjectList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SFDProjectList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Nrmk.IndyFramework.SFDProjectList"; }

 protected:
  explicit SFDProjectList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SFDProjectList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SFDProjectList& from);
  SFDProjectList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SFDProjectList&& from) noexcept
      : SFDProjectList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kListFieldNumber = 1,
  };
  // string list = 1;
  void clear_list() ;
  const ::std::string& list() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_list(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_list();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_list();
  void set_allocated_list(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_list() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_list(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_list();

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDProjectList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 46,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SFDProjectList& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr list_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SFDProjectList_class_data_;
// -------------------------------------------------------------------

class SFDAutoSet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDAutoSet) */ {
 public:
  inline SFDAutoSet() : SFDAutoSet(nullptr) {}
  ~SFDAutoSet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SFDAutoSet* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SFDAutoSet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SFDAutoSet(::google::protobuf::internal::ConstantInitialized);

  inline SFDAutoSet(const SFDAutoSet& from) : SFDAutoSet(nullptr, from) {}
  inline SFDAutoSet(SFDAutoSet&& from) noexcept
      : SFDAutoSet(nullptr, ::std::move(from)) {}
  inline SFDAutoSet& operator=(const SFDAutoSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDAutoSet& operator=(SFDAutoSet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDAutoSet& default_instance() {
    return *reinterpret_cast<const SFDAutoSet*>(
        &_SFDAutoSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(SFDAutoSet& a, SFDAutoSet& b) { a.Swap(&b); }
  inline void Swap(SFDAutoSet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDAutoSet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDAutoSet* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SFDAutoSet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDAutoSet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SFDAutoSet& from) { SFDAutoSet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SFDAutoSet* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Nrmk.IndyFramework.SFDAutoSet"; }

 protected:
  explicit SFDAutoSet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SFDAutoSet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SFDAutoSet& from);
  SFDAutoSet(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SFDAutoSet&& from) noexcept
      : SFDAutoSet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPnFieldNumber = 2,
    kFnFieldNumber = 3,
    kRnFieldNumber = 4,
    kLoginFieldNumber = 1,
    kIsoFieldNumber = 5,
  };
  // string pn = 2;
  void clear_pn() ;
  const ::std::string& pn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pn();
  void set_allocated_pn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pn();

  public:
  // string fn = 3;
  void clear_fn() ;
  const ::std::string& fn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fn();
  void set_allocated_fn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fn();

  public:
  // string rn = 4;
  void clear_rn() ;
  const ::std::string& rn() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rn(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rn();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rn();
  void set_allocated_rn(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rn() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rn(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rn();

  public:
  // bool login = 1;
  void clear_login() ;
  bool login() const;
  void set_login(bool value);

  private:
  bool _internal_login() const;
  void _internal_set_login(bool value);

  public:
  // bool iso = 5;
  void clear_iso() ;
  bool iso() const;
  void set_iso(bool value);

  private:
  bool _internal_iso() const;
  void _internal_set_iso(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDAutoSet)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SFDAutoSet& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pn_;
    ::google::protobuf::internal::ArenaStringPtr fn_;
    ::google::protobuf::internal::ArenaStringPtr rn_;
    bool login_;
    bool iso_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SFDAutoSet_class_data_;
// -------------------------------------------------------------------

class SFDAccount final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDAccount) */ {
 public:
  inline SFDAccount() : SFDAccount(nullptr) {}
  ~SFDAccount() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SFDAccount* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SFDAccount));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SFDAccount(::google::protobuf::internal::ConstantInitialized);

  inline SFDAccount(const SFDAccount& from) : SFDAccount(nullptr, from) {}
  inline SFDAccount(SFDAccount&& from) noexcept
      : SFDAccount(nullptr, ::std::move(from)) {}
  inline SFDAccount& operator=(const SFDAccount& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDAccount& operator=(SFDAccount&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDAccount& default_instance() {
    return *reinterpret_cast<const SFDAccount*>(
        &_SFDAccount_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SFDAccount& a, SFDAccount& b) { a.Swap(&b); }
  inline void Swap(SFDAccount* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDAccount* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDAccount* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SFDAccount>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDAccount& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SFDAccount& from) { SFDAccount::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SFDAccount* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Nrmk.IndyFramework.SFDAccount"; }

 protected:
  explicit SFDAccount(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SFDAccount(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SFDAccount& from);
  SFDAccount(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SFDAccount&& from) noexcept
      : SFDAccount(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmailFieldNumber = 1,
    kTokenFieldNumber = 2,
  };
  // string email = 1;
  void clear_email() ;
  const ::std::string& email() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_email();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_email();
  void set_allocated_email(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_email() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_email(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_email();

  public:
  // string token = 2;
  void clear_token() ;
  const ::std::string& token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_token();
  void set_allocated_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_token();

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDAccount)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 48,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SFDAccount& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SFDAccount_class_data_;
// -------------------------------------------------------------------

class CriData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.CriData) */ {
 public:
  inline CriData() : CriData(nullptr) {}
  ~CriData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CriData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CriData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CriData(::google::protobuf::internal::ConstantInitialized);

  inline CriData(const CriData& from) : CriData(nullptr, from) {}
  inline CriData(CriData&& from) noexcept
      : CriData(nullptr, ::std::move(from)) {}
  inline CriData& operator=(const CriData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CriData& operator=(CriData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CriData& default_instance() {
    return *reinterpret_cast<const CriData*>(
        &_CriData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CriData& a, CriData& b) { a.Swap(&b); }
  inline void Swap(CriData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CriData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CriData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CriData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CriData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CriData& from) { CriData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CriData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Nrmk.IndyFramework.CriData"; }

 protected:
  explicit CriData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CriData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CriData& from);
  CriData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CriData&& from) noexcept
      : CriData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeFieldNumber = 1,
    kCriFieldNumber = 2,
    kVelRatioFieldNumber = 3,
  };
  // double time = 1;
  void clear_time() ;
  double time() const;
  void set_time(double value);

  private:
  double _internal_time() const;
  void _internal_set_time(double value);

  public:
  // double cri = 2;
  void clear_cri() ;
  double cri() const;
  void set_cri(double value);

  private:
  double _internal_cri() const;
  void _internal_set_cri(double value);

  public:
  // double velRatio = 3;
  void clear_velratio() ;
  double velratio() const;
  void set_velratio(double value);

  private:
  double _internal_velratio() const;
  void _internal_set_velratio(double value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.CriData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CriData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double time_;
    double cri_;
    double velratio_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CriData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SFDAccount

// string email = 1;
inline void SFDAccount::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& SFDAccount::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAccount.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDAccount::set_email(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAccount.email)
}
inline ::std::string* PROTOBUF_NONNULL SFDAccount::mutable_email()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAccount.email)
  return _s;
}
inline const ::std::string& SFDAccount::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void SFDAccount::_internal_set_email(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.email_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDAccount::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.email_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDAccount::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAccount.email)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.email_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.email_.Set("", GetArena());
  }
  return released;
}
inline void SFDAccount::set_allocated_email(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAccount.email)
}

// string token = 2;
inline void SFDAccount::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& SFDAccount::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAccount.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDAccount::set_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAccount.token)
}
inline ::std::string* PROTOBUF_NONNULL SFDAccount::mutable_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAccount.token)
  return _s;
}
inline const ::std::string& SFDAccount::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void SFDAccount::_internal_set_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDAccount::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDAccount::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAccount.token)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.token_.Set("", GetArena());
  }
  return released;
}
inline void SFDAccount::set_allocated_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAccount.token)
}

// -------------------------------------------------------------------

// SFDTarget

// string pn = 1;
inline void SFDTarget::clear_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& SFDTarget::pn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.pn)
  return _internal_pn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDTarget::set_pn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.pn)
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::mutable_pn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.pn)
  return _s;
}
inline const ::std::string& SFDTarget::_internal_pn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pn_.Get();
}
inline void SFDTarget::_internal_set_pn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::_internal_mutable_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDTarget::release_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.pn)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pn_.Set("", GetArena());
  }
  return released;
}
inline void SFDTarget::set_allocated_pn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pn_.IsDefault()) {
    _impl_.pn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.pn)
}

// string fn = 2;
inline void SFDTarget::clear_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& SFDTarget::fn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.fn)
  return _internal_fn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDTarget::set_fn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.fn)
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::mutable_fn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.fn)
  return _s;
}
inline const ::std::string& SFDTarget::_internal_fn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fn_.Get();
}
inline void SFDTarget::_internal_set_fn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::_internal_mutable_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.fn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDTarget::release_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.fn)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.fn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fn_.Set("", GetArena());
  }
  return released;
}
inline void SFDTarget::set_allocated_fn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.fn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fn_.IsDefault()) {
    _impl_.fn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.fn)
}

// string rn = 3;
inline void SFDTarget::clear_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& SFDTarget::rn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.rn)
  return _internal_rn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDTarget::set_rn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.rn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.rn)
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::mutable_rn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_rn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.rn)
  return _s;
}
inline const ::std::string& SFDTarget::_internal_rn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rn_.Get();
}
inline void SFDTarget::_internal_set_rn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.rn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDTarget::_internal_mutable_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.rn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDTarget::release_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.rn)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.rn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rn_.Set("", GetArena());
  }
  return released;
}
inline void SFDTarget::set_allocated_rn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.rn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rn_.IsDefault()) {
    _impl_.rn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.rn)
}

// bool iso = 4;
inline void SFDTarget::clear_iso() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iso_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool SFDTarget::iso() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.iso)
  return _internal_iso();
}
inline void SFDTarget::set_iso(bool value) {
  _internal_set_iso(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.iso)
}
inline bool SFDTarget::_internal_iso() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iso_;
}
inline void SFDTarget::_internal_set_iso(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iso_ = value;
}

// -------------------------------------------------------------------

// CriData

// double time = 1;
inline void CriData::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double CriData::time() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.time)
  return _internal_time();
}
inline void CriData::set_time(double value) {
  _internal_set_time(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.time)
}
inline double CriData::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void CriData::_internal_set_time(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

// double cri = 2;
inline void CriData::clear_cri() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cri_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double CriData::cri() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.cri)
  return _internal_cri();
}
inline void CriData::set_cri(double value) {
  _internal_set_cri(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.cri)
}
inline double CriData::_internal_cri() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cri_;
}
inline void CriData::_internal_set_cri(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cri_ = value;
}

// double velRatio = 3;
inline void CriData::clear_velratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velratio_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double CriData::velratio() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.velRatio)
  return _internal_velratio();
}
inline void CriData::set_velratio(double value) {
  _internal_set_velratio(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.velRatio)
}
inline double CriData::_internal_velratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velratio_;
}
inline void CriData::_internal_set_velratio(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velratio_ = value;
}

// -------------------------------------------------------------------

// SFDProjectList

// string list = 1;
inline void SFDProjectList::clear_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& SFDProjectList::list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDProjectList.list)
  return _internal_list();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDProjectList::set_list(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.list_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDProjectList.list)
}
inline ::std::string* PROTOBUF_NONNULL SFDProjectList::mutable_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_list();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDProjectList.list)
  return _s;
}
inline const ::std::string& SFDProjectList::_internal_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_.Get();
}
inline void SFDProjectList::_internal_set_list(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.list_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDProjectList::_internal_mutable_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.list_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDProjectList::release_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDProjectList.list)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.list_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.list_.Set("", GetArena());
  }
  return released;
}
inline void SFDProjectList::set_allocated_list(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.list_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.list_.IsDefault()) {
    _impl_.list_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDProjectList.list)
}

// -------------------------------------------------------------------

// SFDAutoSet

// bool login = 1;
inline void SFDAutoSet::clear_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool SFDAutoSet::login() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.login)
  return _internal_login();
}
inline void SFDAutoSet::set_login(bool value) {
  _internal_set_login(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.login)
}
inline bool SFDAutoSet::_internal_login() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_;
}
inline void SFDAutoSet::_internal_set_login(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ = value;
}

// string pn = 2;
inline void SFDAutoSet::clear_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& SFDAutoSet::pn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.pn)
  return _internal_pn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_pn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.pn)
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::mutable_pn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.pn)
  return _s;
}
inline const ::std::string& SFDAutoSet::_internal_pn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pn_.Get();
}
inline void SFDAutoSet::_internal_set_pn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::_internal_mutable_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDAutoSet::release_pn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.pn)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pn_.Set("", GetArena());
  }
  return released;
}
inline void SFDAutoSet::set_allocated_pn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pn_.IsDefault()) {
    _impl_.pn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.pn)
}

// string fn = 3;
inline void SFDAutoSet::clear_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& SFDAutoSet::fn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.fn)
  return _internal_fn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_fn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.fn)
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::mutable_fn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.fn)
  return _s;
}
inline const ::std::string& SFDAutoSet::_internal_fn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fn_.Get();
}
inline void SFDAutoSet::_internal_set_fn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::_internal_mutable_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.fn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDAutoSet::release_fn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.fn)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.fn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fn_.Set("", GetArena());
  }
  return released;
}
inline void SFDAutoSet::set_allocated_fn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.fn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fn_.IsDefault()) {
    _impl_.fn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.fn)
}

// string rn = 4;
inline void SFDAutoSet::clear_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rn_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& SFDAutoSet::rn() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.rn)
  return _internal_rn();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_rn(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.rn_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.rn)
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::mutable_rn()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_rn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.rn)
  return _s;
}
inline const ::std::string& SFDAutoSet::_internal_rn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rn_.Get();
}
inline void SFDAutoSet::_internal_set_rn(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.rn_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SFDAutoSet::_internal_mutable_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.rn_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SFDAutoSet::release_rn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.rn)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.rn_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rn_.Set("", GetArena());
  }
  return released;
}
inline void SFDAutoSet::set_allocated_rn(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.rn_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rn_.IsDefault()) {
    _impl_.rn_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.rn)
}

// bool iso = 5;
inline void SFDAutoSet::clear_iso() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iso_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool SFDAutoSet::iso() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.iso)
  return _internal_iso();
}
inline void SFDAutoSet::set_iso(bool value) {
  _internal_set_iso(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.iso)
}
inline bool SFDAutoSet::_internal_iso() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iso_;
}
inline void SFDAutoSet::_internal_set_iso(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iso_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cri_5fmsgs_2eproto_2epb_2eh
