// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cri_msgs.proto

#include "cri_msgs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Nrmk {
namespace IndyFramework {
PROTOBUF_CONSTEXPR SFDAccount::SFDAccount(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.email_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SFDAccountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDAccountDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDAccountDefaultTypeInternal() {}
  union {
    SFDAccount _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDAccountDefaultTypeInternal _SFDAccount_default_instance_;
PROTOBUF_CONSTEXPR SFDTarget::SFDTarget(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.iso_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SFDTargetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDTargetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDTargetDefaultTypeInternal() {}
  union {
    SFDTarget _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDTargetDefaultTypeInternal _SFDTarget_default_instance_;
PROTOBUF_CONSTEXPR CriData::CriData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.time_)*/0
  , /*decltype(_impl_.cri_)*/0
  , /*decltype(_impl_.velratio_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CriDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CriDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CriDataDefaultTypeInternal() {}
  union {
    CriData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CriDataDefaultTypeInternal _CriData_default_instance_;
PROTOBUF_CONSTEXPR SFDProjectList::SFDProjectList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.list_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SFDProjectListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDProjectListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDProjectListDefaultTypeInternal() {}
  union {
    SFDProjectList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDProjectListDefaultTypeInternal _SFDProjectList_default_instance_;
PROTOBUF_CONSTEXPR SFDAutoSet::SFDAutoSet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rn_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.login_)*/false
  , /*decltype(_impl_.iso_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SFDAutoSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDAutoSetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDAutoSetDefaultTypeInternal() {}
  union {
    SFDAutoSet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDAutoSetDefaultTypeInternal _SFDAutoSet_default_instance_;
}  // namespace IndyFramework
}  // namespace Nrmk
static ::_pb::Metadata file_level_metadata_cri_5fmsgs_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_cri_5fmsgs_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_cri_5fmsgs_2eproto = nullptr;

const uint32_t TableStruct_cri_5fmsgs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _impl_.email_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _impl_.token_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.pn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.fn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.rn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.iso_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.time_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.cri_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.velratio_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDProjectList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDProjectList, _impl_.list_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.login_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.pn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.fn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.rn_),
  PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.iso_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Nrmk::IndyFramework::SFDAccount)},
  { 8, -1, -1, sizeof(::Nrmk::IndyFramework::SFDTarget)},
  { 18, -1, -1, sizeof(::Nrmk::IndyFramework::CriData)},
  { 27, -1, -1, sizeof(::Nrmk::IndyFramework::SFDProjectList)},
  { 34, -1, -1, sizeof(::Nrmk::IndyFramework::SFDAutoSet)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Nrmk::IndyFramework::_SFDAccount_default_instance_._instance,
  &::Nrmk::IndyFramework::_SFDTarget_default_instance_._instance,
  &::Nrmk::IndyFramework::_CriData_default_instance_._instance,
  &::Nrmk::IndyFramework::_SFDProjectList_default_instance_._instance,
  &::Nrmk::IndyFramework::_SFDAutoSet_default_instance_._instance,
};

const char descriptor_table_protodef_cri_5fmsgs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016cri_msgs.proto\022\022Nrmk.IndyFramework\"*\n\n"
  "SFDAccount\022\r\n\005email\030\001 \001(\t\022\r\n\005token\030\002 \001(\t"
  "\"<\n\tSFDTarget\022\n\n\002pn\030\001 \001(\t\022\n\n\002fn\030\002 \001(\t\022\n\n"
  "\002rn\030\003 \001(\t\022\013\n\003iso\030\004 \001(\010\"6\n\007CriData\022\014\n\004tim"
  "e\030\001 \001(\001\022\013\n\003cri\030\002 \001(\001\022\020\n\010velRatio\030\003 \001(\001\"\036"
  "\n\016SFDProjectList\022\014\n\004list\030\001 \001(\t\"L\n\nSFDAut"
  "oSet\022\r\n\005login\030\001 \001(\010\022\n\n\002pn\030\002 \001(\t\022\n\n\002fn\030\003 "
  "\001(\t\022\n\n\002rn\030\004 \001(\t\022\013\n\003iso\030\005 \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_cri_5fmsgs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cri_5fmsgs_2eproto = {
    false, false, 316, descriptor_table_protodef_cri_5fmsgs_2eproto,
    "cri_msgs.proto",
    &descriptor_table_cri_5fmsgs_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_cri_5fmsgs_2eproto::offsets,
    file_level_metadata_cri_5fmsgs_2eproto, file_level_enum_descriptors_cri_5fmsgs_2eproto,
    file_level_service_descriptors_cri_5fmsgs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cri_5fmsgs_2eproto_getter() {
  return &descriptor_table_cri_5fmsgs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cri_5fmsgs_2eproto(&descriptor_table_cri_5fmsgs_2eproto);
namespace Nrmk {
namespace IndyFramework {

// ===================================================================

class SFDAccount::_Internal {
 public:
};

SFDAccount::SFDAccount(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDAccount)
}
SFDAccount::SFDAccount(const SFDAccount& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SFDAccount* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.email_){}
    , decltype(_impl_.token_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.email_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_email().empty()) {
    _this->_impl_.email_.Set(from._internal_email(), 
      _this->GetArenaForAllocation());
  }
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDAccount)
}

inline void SFDAccount::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.email_){}
    , decltype(_impl_.token_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.email_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SFDAccount::~SFDAccount() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDAccount)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SFDAccount::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.email_.Destroy();
  _impl_.token_.Destroy();
}

void SFDAccount::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SFDAccount::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDAccount)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.email_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SFDAccount::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string email = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_email();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDAccount.email"));
        } else
          goto handle_unusual;
        continue;
      // string token = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDAccount.token"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SFDAccount::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDAccount)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string email = 1;
  if (!this->_internal_email().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_email().data(), static_cast<int>(this->_internal_email().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDAccount.email");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_email(), target);
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDAccount.token");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_token(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDAccount)
  return target;
}

size_t SFDAccount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDAccount)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string email = 1;
  if (!this->_internal_email().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_email());
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SFDAccount::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SFDAccount::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SFDAccount::GetClassData() const { return &_class_data_; }


void SFDAccount::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SFDAccount*>(&to_msg);
  auto& from = static_cast<const SFDAccount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDAccount)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SFDAccount::CopyFrom(const SFDAccount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SFDAccount::IsInitialized() const {
  return true;
}

void SFDAccount::InternalSwap(SFDAccount* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.email_, lhs_arena,
      &other->_impl_.email_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.token_, lhs_arena,
      &other->_impl_.token_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SFDAccount::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cri_5fmsgs_2eproto_getter, &descriptor_table_cri_5fmsgs_2eproto_once,
      file_level_metadata_cri_5fmsgs_2eproto[0]);
}

// ===================================================================

class SFDTarget::_Internal {
 public:
};

SFDTarget::SFDTarget(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDTarget)
}
SFDTarget::SFDTarget(const SFDTarget& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SFDTarget* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pn_){}
    , decltype(_impl_.fn_){}
    , decltype(_impl_.rn_){}
    , decltype(_impl_.iso_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.pn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pn().empty()) {
    _this->_impl_.pn_.Set(from._internal_pn(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fn().empty()) {
    _this->_impl_.fn_.Set(from._internal_fn(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rn().empty()) {
    _this->_impl_.rn_.Set(from._internal_rn(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.iso_ = from._impl_.iso_;
  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDTarget)
}

inline void SFDTarget::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pn_){}
    , decltype(_impl_.fn_){}
    , decltype(_impl_.rn_){}
    , decltype(_impl_.iso_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.pn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SFDTarget::~SFDTarget() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDTarget)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SFDTarget::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pn_.Destroy();
  _impl_.fn_.Destroy();
  _impl_.rn_.Destroy();
}

void SFDTarget::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SFDTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDTarget)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pn_.ClearToEmpty();
  _impl_.fn_.ClearToEmpty();
  _impl_.rn_.ClearToEmpty();
  _impl_.iso_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SFDTarget::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string pn = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_pn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDTarget.pn"));
        } else
          goto handle_unusual;
        continue;
      // string fn = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_fn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDTarget.fn"));
        } else
          goto handle_unusual;
        continue;
      // string rn = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_rn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDTarget.rn"));
        } else
          goto handle_unusual;
        continue;
      // bool iso = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.iso_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SFDTarget::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDTarget)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string pn = 1;
  if (!this->_internal_pn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pn().data(), static_cast<int>(this->_internal_pn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDTarget.pn");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_pn(), target);
  }

  // string fn = 2;
  if (!this->_internal_fn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fn().data(), static_cast<int>(this->_internal_fn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDTarget.fn");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fn(), target);
  }

  // string rn = 3;
  if (!this->_internal_rn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rn().data(), static_cast<int>(this->_internal_rn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDTarget.rn");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_rn(), target);
  }

  // bool iso = 4;
  if (this->_internal_iso() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_iso(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDTarget)
  return target;
}

size_t SFDTarget::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDTarget)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pn = 1;
  if (!this->_internal_pn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pn());
  }

  // string fn = 2;
  if (!this->_internal_fn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fn());
  }

  // string rn = 3;
  if (!this->_internal_rn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rn());
  }

  // bool iso = 4;
  if (this->_internal_iso() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SFDTarget::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SFDTarget::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SFDTarget::GetClassData() const { return &_class_data_; }


void SFDTarget::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SFDTarget*>(&to_msg);
  auto& from = static_cast<const SFDTarget&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDTarget)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pn().empty()) {
    _this->_internal_set_pn(from._internal_pn());
  }
  if (!from._internal_fn().empty()) {
    _this->_internal_set_fn(from._internal_fn());
  }
  if (!from._internal_rn().empty()) {
    _this->_internal_set_rn(from._internal_rn());
  }
  if (from._internal_iso() != 0) {
    _this->_internal_set_iso(from._internal_iso());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SFDTarget::CopyFrom(const SFDTarget& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SFDTarget::IsInitialized() const {
  return true;
}

void SFDTarget::InternalSwap(SFDTarget* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pn_, lhs_arena,
      &other->_impl_.pn_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fn_, lhs_arena,
      &other->_impl_.fn_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rn_, lhs_arena,
      &other->_impl_.rn_, rhs_arena
  );
  swap(_impl_.iso_, other->_impl_.iso_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SFDTarget::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cri_5fmsgs_2eproto_getter, &descriptor_table_cri_5fmsgs_2eproto_once,
      file_level_metadata_cri_5fmsgs_2eproto[1]);
}

// ===================================================================

class CriData::_Internal {
 public:
};

CriData::CriData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.CriData)
}
CriData::CriData(const CriData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CriData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.time_){}
    , decltype(_impl_.cri_){}
    , decltype(_impl_.velratio_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.time_, &from._impl_.time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.velratio_) -
    reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.velratio_));
  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.CriData)
}

inline void CriData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.time_){0}
    , decltype(_impl_.cri_){0}
    , decltype(_impl_.velratio_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CriData::~CriData() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.CriData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CriData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CriData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CriData::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.CriData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.velratio_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.velratio_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CriData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double cri = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.cri_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double velRatio = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.velratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CriData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.CriData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double time = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_time(), target);
  }

  // double cri = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cri = this->_internal_cri();
  uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_cri(), target);
  }

  // double velRatio = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_velratio = this->_internal_velratio();
  uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_velratio(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.CriData)
  return target;
}

size_t CriData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.CriData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double time = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    total_size += 1 + 8;
  }

  // double cri = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cri = this->_internal_cri();
  uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    total_size += 1 + 8;
  }

  // double velRatio = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_velratio = this->_internal_velratio();
  uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CriData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CriData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CriData::GetClassData() const { return &_class_data_; }


void CriData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CriData*>(&to_msg);
  auto& from = static_cast<const CriData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.CriData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = from._internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cri = from._internal_cri();
  uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    _this->_internal_set_cri(from._internal_cri());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_velratio = from._internal_velratio();
  uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    _this->_internal_set_velratio(from._internal_velratio());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CriData::CopyFrom(const CriData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.CriData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CriData::IsInitialized() const {
  return true;
}

void CriData::InternalSwap(CriData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CriData, _impl_.velratio_)
      + sizeof(CriData::_impl_.velratio_)
      - PROTOBUF_FIELD_OFFSET(CriData, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CriData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cri_5fmsgs_2eproto_getter, &descriptor_table_cri_5fmsgs_2eproto_once,
      file_level_metadata_cri_5fmsgs_2eproto[2]);
}

// ===================================================================

class SFDProjectList::_Internal {
 public:
};

SFDProjectList::SFDProjectList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDProjectList)
}
SFDProjectList::SFDProjectList(const SFDProjectList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SFDProjectList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.list_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.list_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_list().empty()) {
    _this->_impl_.list_.Set(from._internal_list(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDProjectList)
}

inline void SFDProjectList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.list_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.list_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SFDProjectList::~SFDProjectList() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDProjectList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SFDProjectList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.list_.Destroy();
}

void SFDProjectList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SFDProjectList::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDProjectList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SFDProjectList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_list();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDProjectList.list"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SFDProjectList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDProjectList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string list = 1;
  if (!this->_internal_list().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_list().data(), static_cast<int>(this->_internal_list().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDProjectList.list");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_list(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDProjectList)
  return target;
}

size_t SFDProjectList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDProjectList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string list = 1;
  if (!this->_internal_list().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_list());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SFDProjectList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SFDProjectList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SFDProjectList::GetClassData() const { return &_class_data_; }


void SFDProjectList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SFDProjectList*>(&to_msg);
  auto& from = static_cast<const SFDProjectList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDProjectList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_list().empty()) {
    _this->_internal_set_list(from._internal_list());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SFDProjectList::CopyFrom(const SFDProjectList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDProjectList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SFDProjectList::IsInitialized() const {
  return true;
}

void SFDProjectList::InternalSwap(SFDProjectList* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.list_, lhs_arena,
      &other->_impl_.list_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SFDProjectList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cri_5fmsgs_2eproto_getter, &descriptor_table_cri_5fmsgs_2eproto_once,
      file_level_metadata_cri_5fmsgs_2eproto[3]);
}

// ===================================================================

class SFDAutoSet::_Internal {
 public:
};

SFDAutoSet::SFDAutoSet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDAutoSet)
}
SFDAutoSet::SFDAutoSet(const SFDAutoSet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SFDAutoSet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pn_){}
    , decltype(_impl_.fn_){}
    , decltype(_impl_.rn_){}
    , decltype(_impl_.login_){}
    , decltype(_impl_.iso_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.pn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pn().empty()) {
    _this->_impl_.pn_.Set(from._internal_pn(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fn().empty()) {
    _this->_impl_.fn_.Set(from._internal_fn(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rn().empty()) {
    _this->_impl_.rn_.Set(from._internal_rn(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.login_, &from._impl_.login_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.iso_) -
    reinterpret_cast<char*>(&_impl_.login_)) + sizeof(_impl_.iso_));
  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDAutoSet)
}

inline void SFDAutoSet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pn_){}
    , decltype(_impl_.fn_){}
    , decltype(_impl_.rn_){}
    , decltype(_impl_.login_){false}
    , decltype(_impl_.iso_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.pn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rn_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rn_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SFDAutoSet::~SFDAutoSet() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDAutoSet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SFDAutoSet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pn_.Destroy();
  _impl_.fn_.Destroy();
  _impl_.rn_.Destroy();
}

void SFDAutoSet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SFDAutoSet::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDAutoSet)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pn_.ClearToEmpty();
  _impl_.fn_.ClearToEmpty();
  _impl_.rn_.ClearToEmpty();
  ::memset(&_impl_.login_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.iso_) -
      reinterpret_cast<char*>(&_impl_.login_)) + sizeof(_impl_.iso_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SFDAutoSet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool login = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.login_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string pn = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_pn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDAutoSet.pn"));
        } else
          goto handle_unusual;
        continue;
      // string fn = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_fn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDAutoSet.fn"));
        } else
          goto handle_unusual;
        continue;
      // string rn = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_rn();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Nrmk.IndyFramework.SFDAutoSet.rn"));
        } else
          goto handle_unusual;
        continue;
      // bool iso = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.iso_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SFDAutoSet::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDAutoSet)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool login = 1;
  if (this->_internal_login() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_login(), target);
  }

  // string pn = 2;
  if (!this->_internal_pn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pn().data(), static_cast<int>(this->_internal_pn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDAutoSet.pn");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_pn(), target);
  }

  // string fn = 3;
  if (!this->_internal_fn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fn().data(), static_cast<int>(this->_internal_fn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDAutoSet.fn");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_fn(), target);
  }

  // string rn = 4;
  if (!this->_internal_rn().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rn().data(), static_cast<int>(this->_internal_rn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Nrmk.IndyFramework.SFDAutoSet.rn");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_rn(), target);
  }

  // bool iso = 5;
  if (this->_internal_iso() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_iso(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDAutoSet)
  return target;
}

size_t SFDAutoSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDAutoSet)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pn = 2;
  if (!this->_internal_pn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pn());
  }

  // string fn = 3;
  if (!this->_internal_fn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fn());
  }

  // string rn = 4;
  if (!this->_internal_rn().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rn());
  }

  // bool login = 1;
  if (this->_internal_login() != 0) {
    total_size += 1 + 1;
  }

  // bool iso = 5;
  if (this->_internal_iso() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SFDAutoSet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SFDAutoSet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SFDAutoSet::GetClassData() const { return &_class_data_; }


void SFDAutoSet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SFDAutoSet*>(&to_msg);
  auto& from = static_cast<const SFDAutoSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDAutoSet)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pn().empty()) {
    _this->_internal_set_pn(from._internal_pn());
  }
  if (!from._internal_fn().empty()) {
    _this->_internal_set_fn(from._internal_fn());
  }
  if (!from._internal_rn().empty()) {
    _this->_internal_set_rn(from._internal_rn());
  }
  if (from._internal_login() != 0) {
    _this->_internal_set_login(from._internal_login());
  }
  if (from._internal_iso() != 0) {
    _this->_internal_set_iso(from._internal_iso());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SFDAutoSet::CopyFrom(const SFDAutoSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDAutoSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SFDAutoSet::IsInitialized() const {
  return true;
}

void SFDAutoSet::InternalSwap(SFDAutoSet* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pn_, lhs_arena,
      &other->_impl_.pn_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fn_, lhs_arena,
      &other->_impl_.fn_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rn_, lhs_arena,
      &other->_impl_.rn_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.iso_)
      + sizeof(SFDAutoSet::_impl_.iso_)
      - PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.login_)>(
          reinterpret_cast<char*>(&_impl_.login_),
          reinterpret_cast<char*>(&other->_impl_.login_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SFDAutoSet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cri_5fmsgs_2eproto_getter, &descriptor_table_cri_5fmsgs_2eproto_once,
      file_level_metadata_cri_5fmsgs_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Nrmk::IndyFramework::SFDAccount*
Arena::CreateMaybeMessage< ::Nrmk::IndyFramework::SFDAccount >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Nrmk::IndyFramework::SFDAccount >(arena);
}
template<> PROTOBUF_NOINLINE ::Nrmk::IndyFramework::SFDTarget*
Arena::CreateMaybeMessage< ::Nrmk::IndyFramework::SFDTarget >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Nrmk::IndyFramework::SFDTarget >(arena);
}
template<> PROTOBUF_NOINLINE ::Nrmk::IndyFramework::CriData*
Arena::CreateMaybeMessage< ::Nrmk::IndyFramework::CriData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Nrmk::IndyFramework::CriData >(arena);
}
template<> PROTOBUF_NOINLINE ::Nrmk::IndyFramework::SFDProjectList*
Arena::CreateMaybeMessage< ::Nrmk::IndyFramework::SFDProjectList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Nrmk::IndyFramework::SFDProjectList >(arena);
}
template<> PROTOBUF_NOINLINE ::Nrmk::IndyFramework::SFDAutoSet*
Arena::CreateMaybeMessage< ::Nrmk::IndyFramework::SFDAutoSet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Nrmk::IndyFramework::SFDAutoSet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
