// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cri_msgs.proto
// Protobuf C++ Version: 5.27.2

#include "cri_msgs.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {

inline constexpr SFDTarget::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : pn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iso_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SFDTarget::SFDTarget(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SFDTargetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDTargetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDTargetDefaultTypeInternal() {}
  union {
    SFDTarget _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDTargetDefaultTypeInternal _SFDTarget_default_instance_;

inline constexpr SFDProjectList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : list_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SFDProjectList::SFDProjectList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SFDProjectListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDProjectListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDProjectListDefaultTypeInternal() {}
  union {
    SFDProjectList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDProjectListDefaultTypeInternal _SFDProjectList_default_instance_;

inline constexpr SFDAutoSet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : pn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        login_{false},
        iso_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SFDAutoSet::SFDAutoSet(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SFDAutoSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDAutoSetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDAutoSetDefaultTypeInternal() {}
  union {
    SFDAutoSet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDAutoSetDefaultTypeInternal _SFDAutoSet_default_instance_;

inline constexpr SFDAccount::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SFDAccount::SFDAccount(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SFDAccountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFDAccountDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFDAccountDefaultTypeInternal() {}
  union {
    SFDAccount _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFDAccountDefaultTypeInternal _SFDAccount_default_instance_;

inline constexpr CriData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : time_{0},
        cri_{0},
        velratio_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CriData::CriData(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CriDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CriDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CriDataDefaultTypeInternal() {}
  union {
    CriData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CriDataDefaultTypeInternal _CriData_default_instance_;
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cri_5fmsgs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cri_5fmsgs_2eproto = nullptr;
const ::uint32_t
    TableStruct_cri_5fmsgs_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAccount, _impl_.token_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.pn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.fn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.rn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDTarget, _impl_.iso_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.cri_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::CriData, _impl_.velratio_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDProjectList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDProjectList, _impl_.list_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.login_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.pn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.fn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.rn_),
        PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::SFDAutoSet, _impl_.iso_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Nrmk::IndyFramework::SFDAccount)},
        {10, -1, -1, sizeof(::Nrmk::IndyFramework::SFDTarget)},
        {22, -1, -1, sizeof(::Nrmk::IndyFramework::CriData)},
        {33, -1, -1, sizeof(::Nrmk::IndyFramework::SFDProjectList)},
        {42, -1, -1, sizeof(::Nrmk::IndyFramework::SFDAutoSet)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Nrmk::IndyFramework::_SFDAccount_default_instance_._instance,
    &::Nrmk::IndyFramework::_SFDTarget_default_instance_._instance,
    &::Nrmk::IndyFramework::_CriData_default_instance_._instance,
    &::Nrmk::IndyFramework::_SFDProjectList_default_instance_._instance,
    &::Nrmk::IndyFramework::_SFDAutoSet_default_instance_._instance,
};
const char descriptor_table_protodef_cri_5fmsgs_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016cri_msgs.proto\022\022Nrmk.IndyFramework\"*\n\n"
    "SFDAccount\022\r\n\005email\030\001 \001(\t\022\r\n\005token\030\002 \001(\t"
    "\"<\n\tSFDTarget\022\n\n\002pn\030\001 \001(\t\022\n\n\002fn\030\002 \001(\t\022\n\n"
    "\002rn\030\003 \001(\t\022\013\n\003iso\030\004 \001(\010\"6\n\007CriData\022\014\n\004tim"
    "e\030\001 \001(\001\022\013\n\003cri\030\002 \001(\001\022\020\n\010velRatio\030\003 \001(\001\"\036"
    "\n\016SFDProjectList\022\014\n\004list\030\001 \001(\t\"L\n\nSFDAut"
    "oSet\022\r\n\005login\030\001 \001(\010\022\n\n\002pn\030\002 \001(\t\022\n\n\002fn\030\003 "
    "\001(\t\022\n\n\002rn\030\004 \001(\t\022\013\n\003iso\030\005 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_cri_5fmsgs_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cri_5fmsgs_2eproto = {
    false,
    false,
    316,
    descriptor_table_protodef_cri_5fmsgs_2eproto,
    "cri_msgs.proto",
    &descriptor_table_cri_5fmsgs_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_cri_5fmsgs_2eproto::offsets,
    file_level_enum_descriptors_cri_5fmsgs_2eproto,
    file_level_service_descriptors_cri_5fmsgs_2eproto,
};
namespace Nrmk {
namespace IndyFramework {
// ===================================================================

class SFDAccount::_Internal {
 public:
};

SFDAccount::SFDAccount(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDAccount)
}
inline PROTOBUF_NDEBUG_INLINE SFDAccount::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Nrmk::IndyFramework::SFDAccount& from_msg)
      : email_(arena, from.email_),
        token_(arena, from.token_),
        _cached_size_{0} {}

SFDAccount::SFDAccount(
    ::google::protobuf::Arena* arena,
    const SFDAccount& from)
    : ::google::protobuf::Message(arena) {
  SFDAccount* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDAccount)
}
inline PROTOBUF_NDEBUG_INLINE SFDAccount::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : email_(arena),
        token_(arena),
        _cached_size_{0} {}

inline void SFDAccount::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SFDAccount::~SFDAccount() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDAccount)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SFDAccount::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.email_.Destroy();
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SFDAccount::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SFDAccount, _impl_._cached_size_),
              false,
          },
          &SFDAccount::MergeImpl,
          &SFDAccount::kDescriptorMethods,
          &descriptor_table_cri_5fmsgs_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 48, 2> SFDAccount::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SFDAccount_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nrmk::IndyFramework::SFDAccount>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAccount, _impl_.token_)}},
    // string email = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAccount, _impl_.email_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string email = 1;
    {PROTOBUF_FIELD_OFFSET(SFDAccount, _impl_.email_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(SFDAccount, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\5\5\0\0\0\0\0"
    "Nrmk.IndyFramework.SFDAccount"
    "email"
    "token"
  }},
};

PROTOBUF_NOINLINE void SFDAccount::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDAccount)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.email_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SFDAccount::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDAccount)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string email = 1;
  if (!this->_internal_email().empty()) {
    const std::string& _s = this->_internal_email();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDAccount.email");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDAccount.token");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDAccount)
  return target;
}

::size_t SFDAccount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDAccount)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string email = 1;
  if (!this->_internal_email().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_email());
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SFDAccount::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SFDAccount*>(&to_msg);
  auto& from = static_cast<const SFDAccount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDAccount)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SFDAccount::CopyFrom(const SFDAccount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SFDAccount::InternalSwap(SFDAccount* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata SFDAccount::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SFDTarget::_Internal {
 public:
};

SFDTarget::SFDTarget(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDTarget)
}
inline PROTOBUF_NDEBUG_INLINE SFDTarget::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Nrmk::IndyFramework::SFDTarget& from_msg)
      : pn_(arena, from.pn_),
        fn_(arena, from.fn_),
        rn_(arena, from.rn_),
        _cached_size_{0} {}

SFDTarget::SFDTarget(
    ::google::protobuf::Arena* arena,
    const SFDTarget& from)
    : ::google::protobuf::Message(arena) {
  SFDTarget* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.iso_ = from._impl_.iso_;

  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDTarget)
}
inline PROTOBUF_NDEBUG_INLINE SFDTarget::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : pn_(arena),
        fn_(arena),
        rn_(arena),
        _cached_size_{0} {}

inline void SFDTarget::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.iso_ = {};
}
SFDTarget::~SFDTarget() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDTarget)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SFDTarget::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pn_.Destroy();
  _impl_.fn_.Destroy();
  _impl_.rn_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SFDTarget::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_._cached_size_),
              false,
          },
          &SFDTarget::MergeImpl,
          &SFDTarget::kDescriptorMethods,
          &descriptor_table_cri_5fmsgs_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 43, 2> SFDTarget::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SFDTarget_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nrmk::IndyFramework::SFDTarget>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool iso = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SFDTarget, _impl_.iso_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.iso_)}},
    // string pn = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.pn_)}},
    // string fn = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.fn_)}},
    // string rn = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.rn_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string pn = 1;
    {PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.pn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string fn = 2;
    {PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.fn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rn = 3;
    {PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.rn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool iso = 4;
    {PROTOBUF_FIELD_OFFSET(SFDTarget, _impl_.iso_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\34\2\2\2\0\0\0\0"
    "Nrmk.IndyFramework.SFDTarget"
    "pn"
    "fn"
    "rn"
  }},
};

PROTOBUF_NOINLINE void SFDTarget::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDTarget)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pn_.ClearToEmpty();
  _impl_.fn_.ClearToEmpty();
  _impl_.rn_.ClearToEmpty();
  _impl_.iso_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SFDTarget::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDTarget)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string pn = 1;
  if (!this->_internal_pn().empty()) {
    const std::string& _s = this->_internal_pn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDTarget.pn");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string fn = 2;
  if (!this->_internal_fn().empty()) {
    const std::string& _s = this->_internal_fn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDTarget.fn");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string rn = 3;
  if (!this->_internal_rn().empty()) {
    const std::string& _s = this->_internal_rn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDTarget.rn");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bool iso = 4;
  if (this->_internal_iso() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_iso(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDTarget)
  return target;
}

::size_t SFDTarget::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDTarget)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string pn = 1;
  if (!this->_internal_pn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pn());
  }

  // string fn = 2;
  if (!this->_internal_fn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_fn());
  }

  // string rn = 3;
  if (!this->_internal_rn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_rn());
  }

  // bool iso = 4;
  if (this->_internal_iso() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SFDTarget::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SFDTarget*>(&to_msg);
  auto& from = static_cast<const SFDTarget&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDTarget)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pn().empty()) {
    _this->_internal_set_pn(from._internal_pn());
  }
  if (!from._internal_fn().empty()) {
    _this->_internal_set_fn(from._internal_fn());
  }
  if (!from._internal_rn().empty()) {
    _this->_internal_set_rn(from._internal_rn());
  }
  if (from._internal_iso() != 0) {
    _this->_impl_.iso_ = from._impl_.iso_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SFDTarget::CopyFrom(const SFDTarget& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDTarget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SFDTarget::InternalSwap(SFDTarget* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pn_, &other->_impl_.pn_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fn_, &other->_impl_.fn_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rn_, &other->_impl_.rn_, arena);
        swap(_impl_.iso_, other->_impl_.iso_);
}

::google::protobuf::Metadata SFDTarget::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CriData::_Internal {
 public:
};

CriData::CriData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.CriData)
}
CriData::CriData(
    ::google::protobuf::Arena* arena, const CriData& from)
    : CriData(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CriData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CriData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, time_),
           0,
           offsetof(Impl_, velratio_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::velratio_));
}
CriData::~CriData() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.CriData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CriData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CriData::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CriData, _impl_._cached_size_),
              false,
          },
          &CriData::MergeImpl,
          &CriData::kDescriptorMethods,
          &descriptor_table_cri_5fmsgs_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CriData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CriData_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nrmk::IndyFramework::CriData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double time = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(CriData, _impl_.time_)}},
    // double cri = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(CriData, _impl_.cri_)}},
    // double velRatio = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(CriData, _impl_.velratio_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double time = 1;
    {PROTOBUF_FIELD_OFFSET(CriData, _impl_.time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double cri = 2;
    {PROTOBUF_FIELD_OFFSET(CriData, _impl_.cri_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double velRatio = 3;
    {PROTOBUF_FIELD_OFFSET(CriData, _impl_.velratio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CriData::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.CriData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.time_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.velratio_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.velratio_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CriData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.CriData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double time = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_time(), target);
  }

  // double cri = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_cri = this->_internal_cri();
  ::uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_cri(), target);
  }

  // double velRatio = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_velratio = this->_internal_velratio();
  ::uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_velratio(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.CriData)
  return target;
}

::size_t CriData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.CriData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // double time = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    total_size += 9;
  }

  // double cri = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_cri = this->_internal_cri();
  ::uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    total_size += 9;
  }

  // double velRatio = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_velratio = this->_internal_velratio();
  ::uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CriData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CriData*>(&to_msg);
  auto& from = static_cast<const CriData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.CriData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = from._internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    _this->_impl_.time_ = from._impl_.time_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_cri = from._internal_cri();
  ::uint64_t raw_cri;
  memcpy(&raw_cri, &tmp_cri, sizeof(tmp_cri));
  if (raw_cri != 0) {
    _this->_impl_.cri_ = from._impl_.cri_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_velratio = from._internal_velratio();
  ::uint64_t raw_velratio;
  memcpy(&raw_velratio, &tmp_velratio, sizeof(tmp_velratio));
  if (raw_velratio != 0) {
    _this->_impl_.velratio_ = from._impl_.velratio_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CriData::CopyFrom(const CriData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.CriData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CriData::InternalSwap(CriData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CriData, _impl_.velratio_)
      + sizeof(CriData::_impl_.velratio_)
      - PROTOBUF_FIELD_OFFSET(CriData, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::google::protobuf::Metadata CriData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SFDProjectList::_Internal {
 public:
};

SFDProjectList::SFDProjectList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDProjectList)
}
inline PROTOBUF_NDEBUG_INLINE SFDProjectList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Nrmk::IndyFramework::SFDProjectList& from_msg)
      : list_(arena, from.list_),
        _cached_size_{0} {}

SFDProjectList::SFDProjectList(
    ::google::protobuf::Arena* arena,
    const SFDProjectList& from)
    : ::google::protobuf::Message(arena) {
  SFDProjectList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDProjectList)
}
inline PROTOBUF_NDEBUG_INLINE SFDProjectList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : list_(arena),
        _cached_size_{0} {}

inline void SFDProjectList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SFDProjectList::~SFDProjectList() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDProjectList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SFDProjectList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.list_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SFDProjectList::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SFDProjectList, _impl_._cached_size_),
              false,
          },
          &SFDProjectList::MergeImpl,
          &SFDProjectList::kDescriptorMethods,
          &descriptor_table_cri_5fmsgs_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 46, 2> SFDProjectList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SFDProjectList_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nrmk::IndyFramework::SFDProjectList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string list = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SFDProjectList, _impl_.list_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string list = 1;
    {PROTOBUF_FIELD_OFFSET(SFDProjectList, _impl_.list_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\4\0\0\0\0\0\0"
    "Nrmk.IndyFramework.SFDProjectList"
    "list"
  }},
};

PROTOBUF_NOINLINE void SFDProjectList::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDProjectList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SFDProjectList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDProjectList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string list = 1;
  if (!this->_internal_list().empty()) {
    const std::string& _s = this->_internal_list();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDProjectList.list");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDProjectList)
  return target;
}

::size_t SFDProjectList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDProjectList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string list = 1;
  if (!this->_internal_list().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_list());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SFDProjectList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SFDProjectList*>(&to_msg);
  auto& from = static_cast<const SFDProjectList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDProjectList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_list().empty()) {
    _this->_internal_set_list(from._internal_list());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SFDProjectList::CopyFrom(const SFDProjectList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDProjectList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SFDProjectList::InternalSwap(SFDProjectList* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.list_, &other->_impl_.list_, arena);
}

::google::protobuf::Metadata SFDProjectList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SFDAutoSet::_Internal {
 public:
};

SFDAutoSet::SFDAutoSet(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.SFDAutoSet)
}
inline PROTOBUF_NDEBUG_INLINE SFDAutoSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Nrmk::IndyFramework::SFDAutoSet& from_msg)
      : pn_(arena, from.pn_),
        fn_(arena, from.fn_),
        rn_(arena, from.rn_),
        _cached_size_{0} {}

SFDAutoSet::SFDAutoSet(
    ::google::protobuf::Arena* arena,
    const SFDAutoSet& from)
    : ::google::protobuf::Message(arena) {
  SFDAutoSet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, login_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, login_),
           offsetof(Impl_, iso_) -
               offsetof(Impl_, login_) +
               sizeof(Impl_::iso_));

  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.SFDAutoSet)
}
inline PROTOBUF_NDEBUG_INLINE SFDAutoSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : pn_(arena),
        fn_(arena),
        rn_(arena),
        _cached_size_{0} {}

inline void SFDAutoSet::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, login_),
           0,
           offsetof(Impl_, iso_) -
               offsetof(Impl_, login_) +
               sizeof(Impl_::iso_));
}
SFDAutoSet::~SFDAutoSet() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.SFDAutoSet)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SFDAutoSet::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pn_.Destroy();
  _impl_.fn_.Destroy();
  _impl_.rn_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SFDAutoSet::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_._cached_size_),
              false,
          },
          &SFDAutoSet::MergeImpl,
          &SFDAutoSet::kDescriptorMethods,
          &descriptor_table_cri_5fmsgs_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 44, 2> SFDAutoSet::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SFDAutoSet_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nrmk::IndyFramework::SFDAutoSet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool login = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SFDAutoSet, _impl_.login_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.login_)}},
    // string pn = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.pn_)}},
    // string fn = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.fn_)}},
    // string rn = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.rn_)}},
    // bool iso = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SFDAutoSet, _impl_.iso_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.iso_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool login = 1;
    {PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.login_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string pn = 2;
    {PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.pn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string fn = 3;
    {PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.fn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rn = 4;
    {PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.rn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool iso = 5;
    {PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.iso_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\35\0\2\2\2\0\0\0"
    "Nrmk.IndyFramework.SFDAutoSet"
    "pn"
    "fn"
    "rn"
  }},
};

PROTOBUF_NOINLINE void SFDAutoSet::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.SFDAutoSet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pn_.ClearToEmpty();
  _impl_.fn_.ClearToEmpty();
  _impl_.rn_.ClearToEmpty();
  ::memset(&_impl_.login_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.iso_) -
      reinterpret_cast<char*>(&_impl_.login_)) + sizeof(_impl_.iso_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SFDAutoSet::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.SFDAutoSet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool login = 1;
  if (this->_internal_login() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_login(), target);
  }

  // string pn = 2;
  if (!this->_internal_pn().empty()) {
    const std::string& _s = this->_internal_pn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDAutoSet.pn");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string fn = 3;
  if (!this->_internal_fn().empty()) {
    const std::string& _s = this->_internal_fn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDAutoSet.fn");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string rn = 4;
  if (!this->_internal_rn().empty()) {
    const std::string& _s = this->_internal_rn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nrmk.IndyFramework.SFDAutoSet.rn");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // bool iso = 5;
  if (this->_internal_iso() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_iso(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.SFDAutoSet)
  return target;
}

::size_t SFDAutoSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.SFDAutoSet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string pn = 2;
  if (!this->_internal_pn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pn());
  }

  // string fn = 3;
  if (!this->_internal_fn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_fn());
  }

  // string rn = 4;
  if (!this->_internal_rn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_rn());
  }

  // bool login = 1;
  if (this->_internal_login() != 0) {
    total_size += 2;
  }

  // bool iso = 5;
  if (this->_internal_iso() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SFDAutoSet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SFDAutoSet*>(&to_msg);
  auto& from = static_cast<const SFDAutoSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.SFDAutoSet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pn().empty()) {
    _this->_internal_set_pn(from._internal_pn());
  }
  if (!from._internal_fn().empty()) {
    _this->_internal_set_fn(from._internal_fn());
  }
  if (!from._internal_rn().empty()) {
    _this->_internal_set_rn(from._internal_rn());
  }
  if (from._internal_login() != 0) {
    _this->_impl_.login_ = from._impl_.login_;
  }
  if (from._internal_iso() != 0) {
    _this->_impl_.iso_ = from._impl_.iso_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SFDAutoSet::CopyFrom(const SFDAutoSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.SFDAutoSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SFDAutoSet::InternalSwap(SFDAutoSet* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pn_, &other->_impl_.pn_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fn_, &other->_impl_.fn_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rn_, &other->_impl_.rn_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.iso_)
      + sizeof(SFDAutoSet::_impl_.iso_)
      - PROTOBUF_FIELD_OFFSET(SFDAutoSet, _impl_.login_)>(
          reinterpret_cast<char*>(&_impl_.login_),
          reinterpret_cast<char*>(&other->_impl_.login_));
}

::google::protobuf::Metadata SFDAutoSet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_cri_5fmsgs_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
